[build]
builder = "nixpacks"

[build.config]
nixpacks.pkgFlakeUrl = "github:nixos/nixpkgs/nixos-23.11"

[deploy]
buildCommand = "npm run db:push && npm run build"
startCommand = "npm run start"
restartPolicyMaxRetries = 3
